# Project information
site_name: Pynimate
site_url: https://julkaar9.github.io/
site_author: julkar9
site_description: >-
  Pynimate is a python package for statistical data analysis

# Repository
repo_name: julkaar9/pynimate
repo_url: https://github.com/julkaar9/pynimate

# Copyright
copyright: Copyright &copy; 2023 Md Julkarnaeen

theme:
  name: material
  logo: assets/pynimate_logo.png
  favicon: assets/favicon.png
  features: 
    - content.code.annotate 
    - content.tooltips 
    - navigation.indexes 
    - navigation.sections
    - navigation.tabs 
    - navigation.top
    - navigation.tracking 
    - toc.follow
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - User Guide:
    - Getting started: guide/starter.md
    - Dark Mode Example: guide/dark_mode.md
  - Api Reference:
    - Animators:
      - Canvas: reference/canvas.md
      - Baseplot: reference/baseplot.md
      - Barhplot: reference/barhplot.md
      - Barplot: reference/barplot.md
    - Data Modifiers:
      - BaseDatafier: reference/datafiers/base_datafier.md
      - BarDatafier: reference/datafiers/bar_datafier.md
      - Datafier: reference/datafiers/datafier.md
    - Utils: reference/utils.md
# Customization
extra:
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/julkaar9/pynimate
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pynimate/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
plugins:
- mkdocstrings
- search