name: Build distribution
on: [push, pull_request, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade build wheel setuptools

      - name: Build distributions
        run: python -m build

      - name: Publish package to PyPI
        if: github.repository == 'julkaar9/pynimate' && github.event_name =='push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
